### PR TITLE
Initial work on port from Renderer to Handler

### PR DESCRIPTION
**Pull request by hansmbakker**
While `Custom Renderers`  still work in MAUI, it is recommended to [migrate to control handlers](https://learn.microsoft.com/en-us/dotnet/maui/migration/renderer-to-handler?view=net-maui-8.0).

@matmork I believe you tried using this in the past but had some issues with it - in any case I believe I have an initial version working on Android.

I cannot do the iOS version though as I do not have a mac. Would you like to continue from here?

I used [Migrate a Xamarin.Forms custom renderer to a .NET MAUI handler](https://learn.microsoft.com/en-us/dotnet/maui/migration/renderer-to-handler?view=net-maui-8.0) and [Create a custom control using handlers
](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/handlers/create?view=net-maui-8.0) as a reference.

Stuff to do:
- it is quite clear how to work with the property mapping, but I wasn't sure about where to place the commands and methods that were on the control and the renderer. There seemed to be some redundancy or calling vice-versa.
- double-checking the disposing of the objects
- iOS part

### CODE REVIEW

**Comment by matmork** [comment]
Stumbled upon this discussion https://github.com/dotnet/maui/discussions/21918#discussioncomment-9156084

Maybe follow this recommendation instead:

```
If you're developing handlers, then I would just recommend using the natural lifecycle events of each platform.

windows : Loaded/unloaded
Android : DetachedFromWindow
iOS: willMoveToWindow
```

**Comment by hansmbakker** [comment]
@matmork Well done on finishing this and sorry for the late reply, last week was focused on other stuff.

> Stumbled upon this discussion [dotnet/maui#21918 (comment)](https://github.com/dotnet/maui/discussions/21918#discussioncomment-9156084)
> 
> Maybe follow this recommendation instead:
> 
> ```
> If you're developing handlers, then I would just recommend using the natural lifecycle events of each platform.
> 
> windows : Loaded/unloaded
> Android : DetachedFromWindow
> iOS: willMoveToWindow
> ```

Question - I saw you added the `DisconnectHandler();` calls in the `Unload` page events, but what would happen if we used the events above to call the DisconnectHandler() method instead? So that we wouldn't need to manually call it in the pages?

(I'm curious how MAUI does that itself for the builtin controls)

**Comment by matmork** [comment]
I tried to do that but ended up with some unwanted side effects when navigating, mainly on iOS. Since loaded/unloaded are wired directly to those events I have removed the Unload and calls to DisconnectHandler in an upcoming branch. I think Maui mainly relies on the elements ability to be collected by the GC and the DisconnectHandler() must be invoked manually (I would probably do it on page popped)

**Comment by hansmbakker** [comment]
> I tried to do that but ended up with some unwanted side effects when navigating, mainly on iOS.

What were the side effects like?

> Since loaded/unloaded are wired directly to those events I have removed the Unload and calls to DisconnectHandler in an upcoming branch.

Do you mean the `loaded/unloaded` that were in the page XAMLs? What do you mean with `those events`?

> I think Maui mainly relies on the elements ability to be collected by the GC

This is what I didn't get - MAUI also uses handlers for its controls, but i didn't come across needing to call DisconnectHandler until I looked into implementing our own handler.

**Comment by matmork** [comment]
> What were the side effects like?

When navigating from A to B and then back to A the player would be blank since it was disposed. Not 100% sure, but on iOS i don't think `MovedToWindow ` is the right place to dispose/clean up as it is invoked while still in the navigation stack. I would maybe hook into the navigation popped event and do cleanup when a page is removed from the stack

> Do you mean the `loaded/unloaded` that were in the page XAMLs? What do you mean with `those events`?

Yes. `loaded/unloaded` are wired directly to the related platform events

Android: AttachedToWindow
iOS: MovedToWindow
Windows: Loaded

> This is what I didn't get - MAUI also uses handlers for its controls, but i didn't come across needing to call DisconnectHandler until I looked into implementing our own handler.

Good question I don't know how the MAUI internals work but I see the official handlers also make use of the DisconnectHandler pattern: https://github.com/dotnet/maui/blob/main/src/Core/src/Handlers/ScrollView/ScrollViewHandler.Android.cs

Also see other libraries:
https://github.com/FreakyAli/Maui.FreakyControls/blob/master/MAUI.FreakyControls/MAUI.FreakyControls/Platforms/Android/FreakyAutoCompleteViewHandler.android.cs

**Pull request merged**
